excluded:
  - Packages/*/.build # Tuist/SPM cache & build artifacts

opt_in_rules:
  - all

disabled_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anyobject_protocol # deprecated rule
  - attributes # handled by SwiftFormat
  - balanced_xctest_lifecycle # no XCTest/Quick
  - contrasted_opening_brace
  - direct_return
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_xctest_method # no XCTest/Quick
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier # prever acl on member (func/var) instead
  - fallthrough
  - file_types_order
  - ibinspectable_in_extension # no IB
  - inert_defer # deprecated rule
  - large_tuple
  - missing_docs # docs are not mandatory
  - nimble_operator # no XCTest/Quick
  - no_grouping_extension # don't understand the rule
  - no_magic_numbers
  - nslocalizedstring_key # no NSLocalizedString
  - nslocalizedstring_require_bundle # no NSLocalizedString
  - number_separator # conflicts with SwiftFormat rule
  - object_literal
  - one_declaration_per_file
  - opening_brace # does not handle case when type definiton has multiline 'where' clause
  - pattern_matching_keywords
  - prefer_nimble # no XCTest/Quick
  - prefixed_toplevel_constant
  - private_action # no IB
  - private_outlet # no IB
  - private_over_fileprivate
  - private_unit_test # no XCTest/Quick
  - quick_discouraged_call # no XCTest/Quick
  - quick_discouraged_focused_test # no XCTest/Quick
  - quick_discouraged_pending_test # no XCTest/Quick
  - raw_value_for_camel_cased_codable_enum
  - required_deinit
  - required_enum_case # configurable rule; is not used for now
  - self_binding
  - sorted_enum_cases # it's not mandatory for enums to be sorted
  - sorted_imports # does not work well with @testable. Handled by SwiftFormat
  - strict_fileprivate
  - strong_iboutlet # no IB
  - switch_case_on_newline
  - test_case_accessibility # no XCTest/Quick
  # - trailing_closure # could be removed if there're too many false positives
  # - unavailable_function # could be removed if there're too many false positives
  - unused_capture_list # deprecated rule
  - valid_ibinspectable  # no IB
  - vertical_whitespace_between_cases
  - yoda_condition

# rules customization

conditional_returns_on_newline:
  if_only: true

cyclomatic_complexity:
  ignores_case_statements: true

deployment_target:
  iOS_deployment_target: 17.0
  macOS_deployment_target: 14.0

nesting:
  type_level: 2

no_empty_block:
  disabled_block_types: [initializer_bodies]

file_header:
  required_pattern: |
                    \/\/
                    \/\/  Shoppy
                    \/\/  Created by .*?
                    \/\/  Copyright © 2024 Denis Gaskov\. All rights reserved\.
                    \/\/

file_name:
  excluded: ["Package.swift"]

identifier_name:
  excluded: ["^id$", "^ui$"]

indentation_width:
  indentation_width: 2

line_length:
  warning: 120
  ignores_comments: true

switch_case_alignment:
  indented_cases: true
