//
//  Shoppy
//  Created by Denis Gaskov
//  Copyright © 2024 Denis Gaskov. All rights reserved.
//

import ProjectDescription
import ProjectDescriptionHelpers

let fileHeaderTemplate: FileHeaderTemplate = """
//
//  ___WORKSPACENAME___
//  Created by ___FULLUSERNAME___
//  Copyright © ___YEAR___ Denis Gaskov. All rights reserved.
//
"""

let workspace = Workspace(
  name: consts.appName,
  projects: ["."],
  fileHeaderTemplate: fileHeaderTemplate,
  additionalFiles: [
    .folderReference(path: "Docs"),
    "README.md",
    ".*.yml"
  ],
  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
